CREATE DATABASE lista_db;

CREATE TABLE lists (
    id SERIAL PRIMARY KEY,
    list_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)